@aspnetVol1_HostAddress = http://localhost:5042
@existingShirtId = 2

### 1) GET: lista wszystkich koszulek
GET {{aspnetVol1_HostAddress}}/api/shirt

### 2) GET: pojedyncza istniejaca koszulka (id=2)
GET {{aspnetVol1_HostAddress}}/api/shirt/{{existingShirtId}}

### 3) POST: utworz nowa koszulke
POST {{aspnetVol1_HostAddress}}/api/shirt
Content-Type: application/json

{
  "brand": "Michal",
  "color": "Green",
  "size": 42,
  "gender": "Men",
  "price": 300.99
}

> {%
client.global.set("createdShirtId", response.body.shirtId);
%}

### 4) GET: pobierz nowo utworzona koszulke
GET {{aspnetVol1_HostAddress}}/api/shirt/{{createdShirtId}}

### 5) PUT: zaktualizuj nowo utworzona koszulke (ID w URL i body musi byc identyczne!)
PUT {{aspnetVol1_HostAddress}}/api/shirt/{{createdShirtId}}
Content-Type: application/json

{
  "shirtId": {{createdShirtId}},
  "brand": "TestBrandUpdated",
  "color": "Black",
  "size": 44,
  "gender": "Women",
  "price": 199.99
}

### 6) DELETE: usun nowo utworzona koszulke
DELETE {{aspnetVol1_HostAddress}}/api/shirt/{{createdShirtId}}

### 7) GET: sprawdz czy usunieto (powinien byc 404)
GET {{aspnetVol1_HostAddress}}/api/shirt/{{createdShirtId}}
