@aspnetVol1_HostAddress = http://localhost:5042
### GET all shirts
GET {{aspnetVol1_HostAddress}}/api/shirt

### GET shirt with id 10
GET {{aspnetVol1_HostAddress}}/api/shirt/6

### POST a new shirt
POST {{aspnetVol1_HostAddress}}/api/shirt
Content-Type: application/json

{
  "shirtId": 6,
  "brand": "Nikesdada",
  "color": "Blue",
  "size": 34,
  "gender": "women",
  "price": 59.99
}

### PUT update shirt with id 10
PUT {{aspnetVol1_HostAddress}}/api/shirt/10
Content-Type: application/json

{
  "shirtId": 6,
  "brand": "Adiasdlnalksdas",
  "color": "Red",
  "size": 40,
  "gender": "Female",
  "price": 39.99
}
### DELETE shirt with id 10
DELETE {{aspnetVol1_HostAddress}}/api/shirt/10
Content-Type: application/json