// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetVol1.Data;

#nullable disable

namespace aspnetVol1.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspnetVol1.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "Nike",
                            Color = "Red",
                            Gender = "Men",
                            Price = 29.989999999999998,
                            Size = 10
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "Adidas",
                            Color = "Blue",
                            Gender = "Men",
                            Price = 122.88,
                            Size = 22
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "Under Armour",
                            Color = "Green",
                            Gender = "Men",
                            Price = 19.989999999999998,
                            Size = 6
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "Puma",
                            Color = "Black",
                            Gender = "Men",
                            Price = 24.989999999999998,
                            Size = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
